const http=require('http');
const fs=require('fs'); const path=require('path'); const crypto=require('crypto');
const ROOT=__dirname, PUBLIC=path.join(ROOT,'public'), DATA=path.join(ROOT,'data','db.json');
const PORT=process.env.PORT||3000;
const IS_PROD=process.env.NODE_ENV==='production';
const APP_SECRET=process.env.APP_SECRET||crypto.randomBytes(32).toString('hex');
const SUPABASE_URL=String(process.env.SUPABASE_URL||'').replace(/\/$/,'');
const SUPABASE_SECRET_KEY=String(process.env.SUPABASE_SECRET_KEY||'');
const SUPABASE_SERVICE_ROLE_KEY=String(process.env.SUPABASE_SERVICE_ROLE_KEY||'');
const HAS_SUPABASE=Boolean(SUPABASE_URL&&(SUPABASE_SECRET_KEY||SUPABASE_SERVICE_ROLE_KEY));
const SUPABASE_AUTH_ADMIN_KEY=SUPABASE_SERVICE_ROLE_KEY||SUPABASE_SECRET_KEY;
const HASH_SALT=process.env.HASH_SALT||'RazaClasses-Production-Salt-2026';
const SESSION_TTL=Number(process.env.SESSION_TTL||28800);
const MAX_BODY=Number(process.env.MAX_BODY||50*1024*1024);
function hash(s){return crypto.scryptSync(String(s),HASH_SALT,64).toString('hex')}
function id(){return crypto.randomUUID()}
function fresh(){return {admin:{username:'admin',name:'Administrator',photo:null,siteName:'Raza Classes',tagline:'Where Mind Bloom',phone:'',email:'',passwordHash:hash(process.env.ADMIN_PASSWORD||'Admin@12345')},students:[],classes:[],materials:[],assignments:[],tests:[],quizzes:[],notices:[],homeHighlights:[],syllabus:null,examAdda:null}}
function load(){if(!fs.existsSync(path.dirname(DATA)))fs.mkdirSync(path.dirname(DATA),{recursive:true});if(!fs.existsSync(DATA))fs.writeFileSync(DATA,JSON.stringify(fresh(),null,2));let d=JSON.parse(fs.readFileSync(DATA,'utf8'));let f=fresh();for(const k of Object.keys(f))if(d[k]===undefined)d[k]=f[k];if(!Array.isArray(d.classes))d.classes=[];if(!Array.isArray(d.materials))d.materials=[];if(!Array.isArray(d.assignments))d.assignments=[];if(!Array.isArray(d.tests))d.tests=[];if(!Array.isArray(d.quizzes))d.quizzes=[];if(!Array.isArray(d.notices))d.notices=[];if(!Array.isArray(d.homeHighlights))d.homeHighlights=[];return d}
function save(db){const tmp=DATA+'.tmp';fs.writeFileSync(tmp,JSON.stringify(db,null,2),{mode:0o600});fs.renameSync(tmp,DATA)}
let db=load(); const sessions=new Map(); const attempts=new Map(); const loginHits=new Map();
setInterval(()=>{const t=Date.now();for(const [k,v] of sessions)if(t-v.lastSeen>SESSION_TTL*1000)sessions.delete(k)},60000).unref();
function rateLimit(key,limit=12,windowMs=10*60*1000){const now=Date.now(),a=loginHits.get(key)||[];const fresh=a.filter(t=>now-t<windowMs);if(fresh.length>=limit){loginHits.set(key,fresh);return false}fresh.push(now);loginHits.set(key,fresh);return true}
function publicFile(res,file,type){const f=path.join(PUBLIC,file);if(!fs.existsSync(f))return send(res,404,{error:'File not found'});res.writeHead(200,{'Content-Type':type||'application/octet-stream','Cache-Control':'public, max-age=86400'});fs.createReadStream(f).pipe(res)}
function send(res,status,obj,headers={}){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8',...headers});res.end(JSON.stringify(obj))}
function cookie(res,name,value,maxAge=SESSION_TTL){res.setHeader('Set-Cookie',`${name}=${value}; HttpOnly; Path=/; SameSite=Lax; SameSite=Lax; Max-Age=${maxAge}${IS_PROD?' ; Secure':''}`.replace('; SameSite=Lax; SameSite=Lax','; SameSite=Lax'))}
function sid(req){const m=(req.headers.cookie||'').match(/(?:^|;)\s*sid=([^;]+)/);return m&&m[1]}
function auth(req){const b=(req.headers.authorization||'').match(/^Bearer\s+(.+)$/i);const key=(b&&b[1])||sid(req);const u=sessions.get(key);if(!u)return null;if(Date.now()-u.lastSeen>SESSION_TTL*1000){sessions.delete(key);return null}u.lastSeen=Date.now();return u}
function readBody(req){return new Promise((resolve,reject)=>{let a=[],n=0;req.on('data',c=>{n+=c.length;if(n>MAX_BODY){reject(new Error('Body too large'));req.destroy()}else a.push(c)});req.on('end',()=>resolve(Buffer.concat(a)));req.on('error',reject)})}
function jsonBody(req){return readBody(req).then(b=>JSON.parse(b.toString()||'{}'))}
function parseMultipart(buf,ct){const m=String(ct||'').match(/boundary=(?:(?:"([^"]+)")|([^;]+))/i);if(!m)throw Error('Invalid multipart');const boundary=Buffer.from('--'+(m[1]||m[2]));let out={},pos=0;while((pos=buf.indexOf(boundary,pos))!==-1){pos+=boundary.length;if(buf.slice(pos,pos+2).toString()==='--')break;if(buf.slice(pos,pos+2).toString()==='\r\n')pos+=2;let end=buf.indexOf(boundary,pos);if(end<0)break;let part=buf.slice(pos,end-2),sep=part.indexOf('\r\n\r\n');if(sep<0){pos=end;continue}let h=part.slice(0,sep).toString(),data=part.slice(sep+4),nm=(h.match(/name="([^"]+)"/i)||[])[1];if(!nm){pos=end;continue}let fn=(h.match(/filename="([^"]*)"/i)||[])[1];if(fn!==undefined){out[nm]={filename:path.basename(fn),type:(h.match(/Content-Type:\s*([^\r\n]+)/i)||[])[1]||'application/octet-stream',data:data.toString('base64'),size:data.length}}else out[nm]=data.toString('utf8');pos=end}return out}
function safeStudent(s){if(!s)return null;let {passwordHash,...x}=s;return x}
function now(){return new Date()}
async function supa(pathname,options={},key=SUPABASE_SECRET_KEY){
  if(!HAS_SUPABASE) throw new Error('Supabase is not configured');
  const headers={apikey:key,'Content-Type':'application/json',...(options.headers||{})};
  // Legacy service_role keys are JWTs and require Authorization: Bearer.
  // New sb_secret keys are opaque keys and must NOT be sent as Bearer tokens.
  if(key===SUPABASE_SERVICE_ROLE_KEY && SUPABASE_SERVICE_ROLE_KEY){
    headers.Authorization=`Bearer ${SUPABASE_SERVICE_ROLE_KEY}`;
  }
  const r=await fetch(`${SUPABASE_URL}${pathname}`, {...options,headers});
  let data=null; try{data=await r.json()}catch{}
  if(!r.ok){const msg=data?.msg||data?.message||data?.error_description||data?.error||`Supabase request failed (${r.status})`; const e=new Error(msg); e.status=r.status; e.data=data; throw e}
  return data;
}
async function supaCreateUser({email,password,name}){
  return supa('/auth/v1/admin/users',{method:'POST',body:JSON.stringify({email,password,email_confirm:true,user_metadata:{name}})},SUPABASE_AUTH_ADMIN_KEY);
}
async function supaSignIn(email,password){
  return supa('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email,password})});
}
async function supaUpdatePassword(authUserId,password){
  return supa(`/auth/v1/admin/users/${encodeURIComponent(authUserId)}`,{method:'PUT',body:JSON.stringify({password})},SUPABASE_AUTH_ADMIN_KEY);
}
function activeWindow(x){if(!x)return true;let n=now();if(x.openAt&&n<new Date(x.openAt))return false;if(x.closeAt&&n>new Date(x.closeAt))return false;return true}
function targetMatch(n,user){return n.audience==='home'||n.audience==='both'||(n.audience==='students'&&(n.studentIds||[]).includes(user.id))||(n.audience==='class'&&(n.className||'')===(user.className||''))}
function visible(db,user){if(user.role==='admin')return {admin:{username:db.admin.username,name:db.admin.name,photo:db.admin.photo,siteName:db.admin.siteName,tagline:db.admin.tagline,phone:db.admin.phone,email:db.admin.email},students:db.students.map(safeStudent),classes:db.classes,materials:db.materials,assignments:db.assignments,tests:db.tests,quizzes:db.quizzes,notices:db.notices,homeHighlights:db.homeHighlights,syllabus:db.syllabus,examAdda:db.examAdda};let st=db.students.find(x=>x.id===user.id);let notices=db.notices.filter(n=>targetMatch(n,{id:user.id,className:st?.className}));return {student:safeStudent(st),classes:db.classes,materials:db.materials.filter(m=>!m.className||m.className===st?.className),assignments:db.assignments.filter(a=>!a.className||a.className===st?.className).map(a=>({...a,submission:(a.submissions||[]).find(x=>x.studentId===user.id)||null})),tests:db.tests.filter(x=>(!x.className||x.className===st?.className)&&activeWindow(x)),quizzes:db.quizzes.filter(x=>(!x.className||x.className===st?.className)&&activeWindow(x)),notices,syllabus:db.syllabus,examAdda:db.examAdda};}
function requireAdmin(user,res){if(!user||user.role!=='admin'){send(res,403,{error:'Admin access required'});return false}return true}
function requireStudent(user,res){if(!user||user.role!=='student'){send(res,403,{error:'Student access required'});return false}return true}
function route(req,res){
 const u=new URL(req.url,`http://${req.headers.host||'localhost'}`),p=u.pathname,method=req.method;
 res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','SAMEORIGIN');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');
 if(IS_PROD)res.setHeader('Content-Security-Policy',"default-src 'self' 'unsafe-inline' data:; img-src 'self' data: blob:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; connect-src 'self'; frame-ancestors 'self'; base-uri 'self'; form-action 'self'");
 if(method==='GET'&&(p==='/'||p==='/index.html')){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-cache'});return fs.createReadStream(path.join(PUBLIC,'index.html')).pipe(res);}
 if(method==='GET'&&p==='/logo.png')return publicFile(res,'logo.png','image/png');
 if(method==='GET'&&p.startsWith('/assets/')){const rel=p.slice(8).replace(/\.\./g,'');return publicFile(res,rel);}
 if(p==='/health'&&method==='GET')return send(res,200,{ok:true,supabase:HAS_SUPABASE});
 if(p==='/api/me'&&method==='GET')return send(res,200,{user:auth(req)||null});
 if(p==='/api/register'&&method==='POST'){if(!rateLimit('register:'+req.socket.remoteAddress,8))return send(res,429,{error:'Too many registration attempts. Try again later.'});return jsonBody(req).then(async x=>{if(!x.name||!x.email||!x.password||!x.className)return send(res,400,{error:'Name, email, class and password are required'});const email=String(x.email).trim().toLowerCase();if(db.students.some(s=>s.email.toLowerCase()===email))return send(res,409,{error:'Email already registered'});let authUser=null;if(HAS_SUPABASE){try{const created=await supaCreateUser({email,password:String(x.password),name:String(x.name)});authUser=created.user||created}catch(e){if(e.status===422||e.status===400)return send(res,409,{error:e.message||'Email already registered'});throw e}}let st={id:id(),auth_user_id:authUser?.id||null,name:x.name,email,className:x.className,roll:x.roll||'',phone:x.phone||'',photo:null,passwordHash:HAS_SUPABASE?null:hash(x.password),createdAt:new Date().toISOString()};db.students.push(st);save(db);let sv=id();sessions.set(sv,{role:'student',id:st.id,authUserId:st.auth_user_id,name:st.name,lastSeen:Date.now()});cookie(res,'sid',sv);send(res,201,{user:{role:'student',id:st.id,name:st.name}})}).catch(e=>{console.error('register error:',e.message);send(res,e.status===409?409:500,{error:e.status===409?e.message:'Registration failed'})});}
 if(p==='/api/login'&&method==='POST'){if(!rateLimit('login:'+req.socket.remoteAddress,15))return send(res,429,{error:'Too many login attempts. Try again later.'});return jsonBody(req).then(async x=>{let user=null;if(x.role==='admin'){if(x.username===db.admin.username&&x.password&&hash(x.password)===db.admin.passwordHash)user={role:'admin',id:'admin',name:db.admin.name||'Administrator'}}else{const email=String(x.email||'').trim().toLowerCase();let st=db.students.find(s=>s.email.toLowerCase()===email);if(st&&x.password){if(HAS_SUPABASE){try{let authData;if(st.auth_user_id){authData=await supaSignIn(email,String(x.password))}else{if(!st.passwordHash||hash(x.password)!==st.passwordHash)return send(res,401,{error:'Invalid login details'});const created=await supaCreateUser({email,password:String(x.password),name:st.name});authData=await supaSignIn(email,String(x.password));st.auth_user_id=(created.user||created).id;st.passwordHash=null;save(db)}if(authData?.user){user={role:'student',id:st.id,authUserId:authData.user.id,name:st.name}}}catch(e){return send(res,401,{error:'Invalid login details'})}}else if(st.passwordHash&&hash(x.password)===st.passwordHash)user={role:'student',id:st.id,name:st.name}}}if(!user)return send(res,401,{error:'Invalid login details'});let sv=id();sessions.set(sv,{...user,lastSeen:Date.now()});cookie(res,'sid',sv);send(res,200,{user,token:sv})}).catch(()=>send(res,400,{error:'Invalid request'}));}
 if(p==='/api/logout'&&method==='POST'){let s=sid(req);if(s)sessions.delete(s);cookie(res,'sid','',0);return send(res,200,{ok:true})}
 if(p==='/api/public'&&method==='GET'){return send(res,200,{notices:db.notices.filter(n=>n.audience==='home'||n.audience==='both').filter(n=>n.type==='written'||n.type==='image'),homeHighlights:db.homeHighlights})}
 const user=auth(req); if(p==='/api/data'&&method==='GET'){if(!user)return send(res,401,{error:'Login required'});return send(res,200,visible(db,user))}
 if(!user)return send(res,401,{error:'Login required'});
 if(p==='/api/profile'&&method==='POST'&&requireStudent(user,res))return readBody(req).then(b=>{let x=parseMultipart(b,req.headers['content-type']);let st=db.students.find(s=>s.id===user.id);if(x.name)st.name=x.name;if(x.className)st.className=x.className;if(x.roll!==undefined)st.roll=x.roll;if(x.phone!==undefined)st.phone=x.phone;if(x.photo?.data)st.photo=x.photo;save(db);send(res,200,{student:safeStudent(st)})}).catch(()=>send(res,400,{error:'Profile update failed'}));
 if(p==='/api/password'&&method==='POST')return jsonBody(req).then(x=>{if(!x.newPassword||x.newPassword.length<6)return send(res,400,{error:'Password must be at least 6 characters'});if(user.role==='admin'){if(x.currentPassword&&hash(x.currentPassword)!==db.admin.passwordHash)return send(res,401,{error:'Current password incorrect'});db.admin.passwordHash=hash(x.newPassword)}else{let st=db.students.find(s=>s.id===user.id);if(!st||hash(x.currentPassword||'')!==st.passwordHash)return send(res,401,{error:'Current password incorrect'});st.passwordHash=hash(x.newPassword)}save(db);send(res,200,{ok:true})}).catch(()=>send(res,400,{error:'Invalid request'}));
 if(user.role==='student'){
  if(p==='/api/assignment/submit'&&method==='POST')return readBody(req).then(b=>{let x=parseMultipart(b,req.headers['content-type']),a=db.assignments.find(a=>a.id===x.assignmentId);if(!a)return send(res,404,{error:'Assignment not found'});a.submissions=a.submissions||[];a.submissions=a.submissions.filter(s=>s.studentId!==user.id);a.submissions.push({studentId:user.id,note:x.note||'',file:x.file||null,submittedAt:new Date().toISOString()});save(db);send(res,200,{ok:true})}).catch(()=>send(res,400,{error:'Submission failed'}));
  if(p==='/api/assessment/start'&&method==='POST')return jsonBody(req).then(x=>{let key=x.type==='quiz'?'quizzes':'tests',item=db[key].find(z=>z.id===x.id);if(!item)return send(res,404,{error:'Assessment not found'});if(!item.published||!activeWindow(item))return send(res,400,{error:'This assessment is not open'});let startedAt=new Date().toISOString();attempts.set(user.id+':'+x.type+':'+x.id,{startedAt});send(res,200,{startedAt,duration:Number(item.duration||0),closeAt:item.closeAt||''})});
  for(const typ of ['test','quiz'])if(p===`/api/${typ}/submit`&&method==='POST')return jsonBody(req).then(x=>{let key=typ==='test'?'tests':'quizzes',item=db[key].find(z=>z.id===x[typ+'Id']);if(!item)return send(res,404,{error:`${typ} not found`});if(!item.published||!activeWindow(item))return send(res,400,{error:`${typ} is not open`});let a=attempts.get(user.id+':'+typ+':'+item.id);if(item.duration&&a&&Date.now()-new Date(a.startedAt).getTime()>Number(item.duration)*60000+5000)return send(res,400,{error:`Time limit of ${item.duration} minutes exceeded`});let score=0,autoTotal=0;(item.questions||[]).forEach((q,i)=>{if(['mcq','very_short','short'].includes(q.type)){autoTotal++;if(String(x.answers?.[i]??'').trim().toLowerCase()===String(q.answer??'').trim().toLowerCase())score++}});item.submissions=item.submissions||[];item.submissions.push({studentId:user.id,answers:x.answers||[],score,autoTotal,submittedAt:new Date().toISOString()});attempts.delete(user.id+':'+typ+':'+item.id);save(db);send(res,200,{score,total:autoTotal,manual:(item.questions||[]).length-autoTotal})});
  return send(res,403,{error:'Not allowed'});
 }
 // admin
 if(!requireAdmin(user,res))return;
 if(p==='/api/admin/student'&&method==='POST')return jsonBody(req).then(async x=>{if(!x.name||!x.email||!x.password||!x.className)return send(res,400,{error:'Required fields missing'});const email=String(x.email).trim().toLowerCase();if(db.students.some(s=>s.email.toLowerCase()===email))return send(res,409,{error:'Email already registered'});let authUser=null;if(HAS_SUPABASE){try{const created=await supaCreateUser({email,password:String(x.password),name:String(x.name)});authUser=created.user||created}catch(e){return send(res,409,{error:e.message||'Could not create Auth user'})}}let st={id:id(),auth_user_id:authUser?.id||null,name:x.name,email,className:x.className,roll:x.roll||'',phone:x.phone||'',photo:null,passwordHash:HAS_SUPABASE?null:hash(x.password),createdAt:new Date().toISOString()};db.students.push(st);save(db);send(res,201,{student:safeStudent(st)})});
 if(p==='/api/admin/student/delete'&&method==='POST')return jsonBody(req).then(x=>{db.students=db.students.filter(s=>s.id!==x.id);save(db);send(res,200,{ok:true})});
 if(p==='/api/admin/student/reset'&&method==='POST')return jsonBody(req).then(async x=>{let st=db.students.find(s=>s.id===x.id);if(!st)return send(res,404,{error:'Student not found'});const pwd=x.password||'Student@123';if(HAS_SUPABASE&&st.auth_user_id){await supaUpdatePassword(st.auth_user_id,pwd);st.passwordHash=null}else st.passwordHash=hash(pwd);save(db);send(res,200,{ok:true,tempPassword:pwd})}).catch(()=>send(res,400,{error:'Password reset failed'}));
 if(p==='/api/admin/class'&&method==='POST')return jsonBody(req).then(x=>{if(!x.name||!x.subject)return send(res,400,{error:'Class and subject required'});db.classes.push({id:id(),name:x.name,subject:x.subject,chapters:[],createdAt:new Date().toISOString()});save(db);send(res,201,{ok:true})});
 if(p==='/api/admin/chapter'&&method==='POST')return jsonBody(req).then(x=>{let c=db.classes.find(c=>c.id===x.classId);if(!c)return send(res,404,{error:'Class not found'});c.chapters=c.chapters||[];c.chapters.push({id:id(),name:x.name,createdAt:new Date().toISOString()});save(db);send(res,201,{ok:true})});
 if(p==='/api/admin/material'&&method==='POST')return readBody(req).then(b=>{let x=parseMultipart(b,req.headers['content-type']);if(!x.title||!x.file)return send(res,400,{error:'Title and file required'});db.materials.unshift({id:id(),title:x.title,kind:x.kind||'Study Material',className:x.className||'',subject:x.subject||'',chapterId:x.chapterId||'',description:x.description||'',file:x.file,createdAt:new Date().toISOString()});save(db);send(res,201,{ok:true})}).catch(()=>send(res,400,{error:'Material upload failed'}));
 if(p==='/api/admin/assignment'&&method==='POST')return readBody(req).then(b=>{let x=parseMultipart(b,req.headers['content-type']);if(!x.title||!x.file)return send(res,400,{error:'Title and file required'});db.assignments.unshift({id:id(),title:x.title,description:x.description||'',className:x.className||'',dueDate:x.dueDate||'',file:x.file,submissions:[],createdAt:new Date().toISOString()});save(db);send(res,201,{ok:true})}).catch(()=>send(res,400,{error:'Assignment upload failed'}));
 if(p==='/api/admin/assessment'&&method==='POST')return jsonBody(req).then(x=>{let key=x.type==='quiz'?'quizzes':'tests';if(!x.title)return send(res,400,{error:'Title required'});let allowed=['mcq','very_short','short','long','case_study','figure'];let questions=(x.questions||[]).map(q=>{let type=allowed.includes(q.type)?q.type:'mcq';return {...q,type,options:type==='mcq'?[...(q.options||[]).slice(0,4)]:[],answer:q.answer||'',figure:q.figure||null,caseStudy:q.caseStudy||''}});db[key].unshift({id:id(),title:x.title,className:x.className||'',description:x.description||'',duration:Number(x.duration||0),openAt:x.openAt||'',closeAt:x.closeAt||'',published:!!x.published,questions,submissions:[],createdAt:new Date().toISOString()});save(db);send(res,201,{ok:true})});
 if(p==='/api/admin/notice'&&method==='POST')return readBody(req).then(b=>{let x=parseMultipart(b,req.headers['content-type']);if(!x.title)return send(res,400,{error:'Title required'});let n={id:id(),type:x.type||'written',title:x.title,body:x.body||'',audience:x.audience||'students',className:x.className||'',studentIds:x.studentIds?String(x.studentIds).split(',').map(s=>s.trim()).filter(Boolean):[],file:x.file||null,createdAt:new Date().toISOString()};db.notices.unshift(n);save(db);send(res,201,{ok:true})}).catch(()=>send(res,400,{error:'Notice save failed'}));
 if(p==='/api/admin/notice/delete'&&method==='POST')return jsonBody(req).then(x=>{db.notices=db.notices.filter(n=>n.id!==x.id);save(db);send(res,200,{ok:true})});
 if(p==='/api/admin/assessment/update'&&method==='POST')return jsonBody(req).then(x=>{let arr=x.key==='quizzes'?db.quizzes:db.tests,item=arr.find(a=>a.id===x.id);if(!item)return send(res,404,{error:'Assessment not found'});Object.assign(item,{openAt:x.data?.openAt||'',closeAt:x.data?.closeAt||'',duration:Number(x.data?.duration||0),published:!!x.data?.published});save(db);send(res,200,{ok:true})});
 if(p==='/api/admin/settings'&&method==='POST')return readBody(req).then(b=>{let x=parseMultipart(b,req.headers['content-type']);if(x.username)db.admin.username=x.username;if(x.name!==undefined)db.admin.name=x.name;if(x.siteName!==undefined)db.admin.siteName=x.siteName;if(x.tagline!==undefined)db.admin.tagline=x.tagline;if(x.phone!==undefined)db.admin.phone=x.phone;if(x.email!==undefined)db.admin.email=x.email;if(x.photo?.data)db.admin.photo=x.photo;if(x.password){if(x.password.length<6)return send(res,400,{error:'Password must be at least 6 characters'});db.admin.passwordHash=hash(x.password)}save(db);send(res,200,{ok:true})}).catch(()=>send(res,400,{error:'Settings save failed'}));
 if(p==='/api/admin/syllabus'&&method==='POST')return readBody(req).then(b=>{let x=parseMultipart(b,req.headers['content-type']);if(!x.file)return send(res,400,{error:'PDF required'});db.syllabus={title:x.title||'Syllabus',className:x.className||'',file:x.file,updatedAt:new Date().toISOString()};save(db);send(res,200,{ok:true})}).catch(()=>send(res,400,{error:'Syllabus upload failed'}));
 if(p==='/api/admin/exam-adda'&&method==='POST')return readBody(req).then(b=>{let x=parseMultipart(b,req.headers['content-type']);if(!x.file)return send(res,400,{error:'Main PDF required'});db.examAdda={title:x.title||'Exam Adda',description:x.description||'',file:x.file,updatedAt:new Date().toISOString()};save(db);send(res,200,{ok:true})}).catch(()=>send(res,400,{error:'Exam Adda upload failed'}));
 if(p==='/api/admin/home-highlight'&&method==='POST')return readBody(req).then(b=>{let x=parseMultipart(b,req.headers['content-type']);if(!x.file)return send(res,400,{error:'Image required'});db.homeHighlights.unshift({id:id(),title:x.title||'Special Moment',description:x.description||'',file:x.file,createdAt:new Date().toISOString()});save(db);send(res,201,{ok:true})}).catch(()=>send(res,400,{error:'Home image upload failed'}));
 if(p==='/api/admin/home-highlight/delete'&&method==='POST')return jsonBody(req).then(x=>{db.homeHighlights=db.homeHighlights.filter(h=>h.id!==x.id);save(db);send(res,200,{ok:true})});
 if(p==='/api/admin/submissions'&&method==='GET')return send(res,200,{assignments:db.assignments,tests:db.tests,quizzes:db.quizzes});
 return send(res,404,{error:'Not found'});
}
function startServer(port){
  const server=http.createServer((req,res)=>{try{route(req,res)}catch(e){console.error(e);if(!res.headersSent)send(res,500,{error:'Server error'})}});
  server.once('error',(err)=>{
    if(err.code==='EADDRINUSE' && !process.env.PORT){
      console.log(`Port ${port} is busy. Trying ${port+1}...`);
      startServer(port+1);
    }else{console.error(err);process.exit(1)}
  });
  server.listen(port,'0.0.0.0',()=>console.log(`Raza Classes running on http://0.0.0.0:${port}`));
}
startServer(Number(PORT));
